# filesystem bytes to utilize
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: azure-instance-io-stress
    spec:
      components:
        env:
        - name: FILESYSTEM_UTILIZATION_BYTES
          VALUE: '1024'
        # name of the azure instance
        - name: AZURE_INSTANCE_NAMES
          value: 'instance-1'
        # resource group for the azure instance
        - name: RESOURCE_GROUP
          value: 'rg-azure'