# volume path to be used for io stress
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: azure-instance-io-stress
    spec:
      components:
        env:
        - name: VOLUME_MOUNT_PATH
          VALUE: '/tmp'
        # name of the azure instance
        - name: AZURE_INSTANCE_NAMES
          value: 'instance-1'
        # resource group for the azure instance
        - name: RESOURCE_GROUP
          value: 'rg-azure'