# induces dns chaos on the VMWare VM
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: vmware-engine
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: vmware-dns-chaos
    spec:
      components:
        env:
        # MOID of the VM
        - name: PORT
          value: '54'

        - name: VM_NAME
          value: 'vm-1,vm-2'

        - name: TOTAL_CHAOS_DURATION
          VALUE: '60'

        - name: VM_USER_NAME
          value: 'ubuntu,debian'

        - name: VM_PASSWORD
          value: '123,123'